FROM python:3.10-slim

WORKDIR /

COPY requirements.txt requirements.txt

RUN pip install -r requirements.txt

COPY .

EXPOSE 8000
EXPOSE 8051
EXPOSE 8050

ENV PORT 8051
ENV HOST 0.0.0.0

CMD [ "sh", "-c", "streamlit run --server.port ${PORT} --server.address ${HOST} '/reports/Análise.py'" ]